#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : plasma-pa
Version  : 5.23.5
Release  : 56
URL      : https://download.kde.org/stable/plasma/5.23.5/plasma-pa-5.23.5.tar.xz
Source0  : https://download.kde.org/stable/plasma/5.23.5/plasma-pa-5.23.5.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause GPL-2.0 GPL-3.0 LGPL-2.0 LGPL-2.1 LGPL-3.0
Requires: plasma-pa-data = %{version}-%{release}
Requires: plasma-pa-lib = %{version}-%{release}
Requires: plasma-pa-license = %{version}-%{release}
Requires: plasma-pa-locales = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules-data
BuildRequires : kdoctools-dev
BuildRequires : kglobalaccel-dev
BuildRequires : ki18n-dev
BuildRequires : kirigami2-dev
BuildRequires : libcanberra-dev
BuildRequires : pkgconfig(gconf-2.0)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(gobject-2.0)
BuildRequires : pkgconfig(libpulse)
BuildRequires : pkgconfig(libpulse-mainloop-glib)

%description
No detailed description available

%package data
Summary: data components for the plasma-pa package.
Group: Data

%description data
data components for the plasma-pa package.


%package doc
Summary: doc components for the plasma-pa package.
Group: Documentation

%description doc
doc components for the plasma-pa package.


%package lib
Summary: lib components for the plasma-pa package.
Group: Libraries
Requires: plasma-pa-data = %{version}-%{release}
Requires: plasma-pa-license = %{version}-%{release}

%description lib
lib components for the plasma-pa package.


%package license
Summary: license components for the plasma-pa package.
Group: Default

%description license
license components for the plasma-pa package.


%package locales
Summary: locales components for the plasma-pa package.
Group: Default

%description locales
locales components for the plasma-pa package.


%prep
%setup -q -n plasma-pa-5.23.5
cd %{_builddir}/plasma-pa-5.23.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1641317972
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1641317972
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/plasma-pa
cp %{_builddir}/plasma-pa-5.23.5/LICENSES/BSD-3-Clause.txt %{buildroot}/usr/share/package-licenses/plasma-pa/9950d3fdce1cff1f71212fb5abd31453c6ee2f8c
cp %{_builddir}/plasma-pa-5.23.5/LICENSES/GPL-2.0-only.txt %{buildroot}/usr/share/package-licenses/plasma-pa/3e8971c6c5f16674958913a94a36b1ea7a00ac46
cp %{_builddir}/plasma-pa-5.23.5/LICENSES/GPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/plasma-pa/2123756e0b1fc8243547235a33c0fcabfe3b9a51
cp %{_builddir}/plasma-pa-5.23.5/LICENSES/LGPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/plasma-pa/a4c60b3fefda228cd7439d3565df043192fef137
cp %{_builddir}/plasma-pa-5.23.5/LICENSES/LGPL-2.1-only.txt %{buildroot}/usr/share/package-licenses/plasma-pa/81b58c89ceef8e9f8bd5d00a287edbd15f9d3567
cp %{_builddir}/plasma-pa-5.23.5/LICENSES/LGPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/plasma-pa/19d98e1b6f8ef12849ea4012a052d3907f336c91
cp %{_builddir}/plasma-pa-5.23.5/LICENSES/LicenseRef-KDE-Accepted-GPL.txt %{buildroot}/usr/share/package-licenses/plasma-pa/7d9831e05094ce723947d729c2a46a09d6e90275
cp %{_builddir}/plasma-pa-5.23.5/LICENSES/LicenseRef-KDE-Accepted-GPL.txt %{buildroot}/usr/share/package-licenses/plasma-pa/7d9831e05094ce723947d729c2a46a09d6e90275
cp %{_builddir}/plasma-pa-5.23.5/LICENSES/LicenseRef-KDE-Accepted-LGPL.txt %{buildroot}/usr/share/package-licenses/plasma-pa/e458941548e0864907e654fa2e192844ae90fc32
cp %{_builddir}/plasma-pa-5.23.5/LICENSES/LicenseRef-KDE-Accepted-LGPL.txt %{buildroot}/usr/share/package-licenses/plasma-pa/e458941548e0864907e654fa2e192844ae90fc32
cp %{_builddir}/plasma-pa-5.23.5/cmake/COPYING-CMAKE-SCRIPTS %{buildroot}/usr/share/package-licenses/plasma-pa/ff3ed70db4739b3c6747c7f624fe2bad70802987
pushd clr-build
%make_install
popd
%find_lang kcm_pulseaudio
%find_lang plasma_applet_org.kde.plasma.volume

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/kconf_update/disable_kmix.upd
/usr/share/kconf_update/plasmaVolumeDisableKMixAutostart.pl
/usr/share/kde4/apps/kconf_update/disable_kmix.upd
/usr/share/kde4/apps/kconf_update/plasmaVolumeDisableKMixAutostart.pl
/usr/share/kpackage/kcms/kcm_pulseaudio/contents/code/icon.js
/usr/share/kpackage/kcms/kcm_pulseaudio/contents/ui/CardListItem.qml
/usr/share/kpackage/kcms/kcm_pulseaudio/contents/ui/DeviceComboBox.qml
/usr/share/kpackage/kcms/kcm_pulseaudio/contents/ui/DeviceListItem.qml
/usr/share/kpackage/kcms/kcm_pulseaudio/contents/ui/MuteButton.qml
/usr/share/kpackage/kcms/kcm_pulseaudio/contents/ui/StreamListItem.qml
/usr/share/kpackage/kcms/kcm_pulseaudio/contents/ui/VolumeSlider.qml
/usr/share/kpackage/kcms/kcm_pulseaudio/contents/ui/main.qml
/usr/share/kpackage/kcms/kcm_pulseaudio/metadata.desktop
/usr/share/kpackage/kcms/kcm_pulseaudio/metadata.json
/usr/share/kservices5/kcm_pulseaudio.desktop
/usr/share/kservices5/plasma-applet-org.kde.plasma.volume.desktop
/usr/share/metainfo/org.kde.plasma.volume.appdata.xml
/usr/share/plasma/plasmoids/org.kde.plasma.volume/contents/code/icon.js
/usr/share/plasma/plasmoids/org.kde.plasma.volume/contents/config/config.qml
/usr/share/plasma/plasmoids/org.kde.plasma.volume/contents/config/main.xml
/usr/share/plasma/plasmoids/org.kde.plasma.volume/contents/ui/ConfigGeneral.qml
/usr/share/plasma/plasmoids/org.kde.plasma.volume/contents/ui/DeviceListItem.qml
/usr/share/plasma/plasmoids/org.kde.plasma.volume/contents/ui/Header.qml
/usr/share/plasma/plasmoids/org.kde.plasma.volume/contents/ui/ListItemBase.qml
/usr/share/plasma/plasmoids/org.kde.plasma.volume/contents/ui/SmallToolButton.qml
/usr/share/plasma/plasmoids/org.kde.plasma.volume/contents/ui/StreamListItem.qml
/usr/share/plasma/plasmoids/org.kde.plasma.volume/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.plasma.volume/metadata.desktop
/usr/share/plasma/plasmoids/org.kde.plasma.volume/metadata.json

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/HTML/ca/kcontrol/plasma-pa/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/plasma-pa/index.docbook
/usr/share/doc/HTML/de/kcontrol/plasma-pa/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/plasma-pa/index.docbook
/usr/share/doc/HTML/en/kcontrol/plasma-pa/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/plasma-pa/index.docbook
/usr/share/doc/HTML/es/kcontrol/plasma-pa/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol/plasma-pa/index.docbook
/usr/share/doc/HTML/id/kcontrol/plasma-pa/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/plasma-pa/index.docbook
/usr/share/doc/HTML/it/kcontrol/plasma-pa/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/plasma-pa/index.docbook
/usr/share/doc/HTML/nl/kcontrol/plasma-pa/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/plasma-pa/index.docbook
/usr/share/doc/HTML/pt/kcontrol/plasma-pa/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/plasma-pa/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/plasma-pa/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/plasma-pa/index.docbook
/usr/share/doc/HTML/ru/kcontrol/plasma-pa/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/plasma-pa/index.docbook
/usr/share/doc/HTML/sv/kcontrol/plasma-pa/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/plasma-pa/index.docbook
/usr/share/doc/HTML/uk/kcontrol/plasma-pa/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/plasma-pa/index.docbook

%files lib
%defattr(-,root,root,-)
/usr/lib64/qt5/plugins/kcms/kcm_pulseaudio.so
/usr/lib64/qt5/qml/org/kde/plasma/private/volume/PulseObjectFilterModel.qml
/usr/lib64/qt5/qml/org/kde/plasma/private/volume/libplasma-volume-declarative.so
/usr/lib64/qt5/qml/org/kde/plasma/private/volume/qmldir

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/plasma-pa/19d98e1b6f8ef12849ea4012a052d3907f336c91
/usr/share/package-licenses/plasma-pa/2123756e0b1fc8243547235a33c0fcabfe3b9a51
/usr/share/package-licenses/plasma-pa/3e8971c6c5f16674958913a94a36b1ea7a00ac46
/usr/share/package-licenses/plasma-pa/7d9831e05094ce723947d729c2a46a09d6e90275
/usr/share/package-licenses/plasma-pa/81b58c89ceef8e9f8bd5d00a287edbd15f9d3567
/usr/share/package-licenses/plasma-pa/9950d3fdce1cff1f71212fb5abd31453c6ee2f8c
/usr/share/package-licenses/plasma-pa/a4c60b3fefda228cd7439d3565df043192fef137
/usr/share/package-licenses/plasma-pa/e458941548e0864907e654fa2e192844ae90fc32
/usr/share/package-licenses/plasma-pa/ff3ed70db4739b3c6747c7f624fe2bad70802987

%files locales -f kcm_pulseaudio.lang -f plasma_applet_org.kde.plasma.volume.lang
%defattr(-,root,root,-)

